Added ABN App Version
notifyme-app/notifyme-app-android pull request #10
Opened 2020-12-15 16:43 UTC by gallmann-ubique

2020-12-15 18:52 UTC, martinalig approved these changes

2020-12-16 08:06 UTC, simonroesch requested changes
Github Action to build Abnahme version is missing.

2020-12-16 08:06 UTC, simonroesch commented on app/src/main/java/ch/ubique/notifyme/app/MainFragment.java
> +		if (BuildConfig.FLAVOR.equals("dev")) {
Abnahme ist auch keine produktive Umgebung, er Hinweis sollte also schon auf allen Non-Prod Umgebungen angezeigt weren!

2020-12-16 11:58 UTC, simonroesch approved these changes

2020-12-16 11:59 UTC, merged